"""empty message

Revision ID: 5689970c125c
Revises: 
Create Date: 2019-07-09 15:45:46.344906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5689970c125c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('air_quality', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurments')
    # ### end Alembic commands ###
